# Generated by Django 5.1 on 2025-08-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
