# Generated by Django 5.1 on 2025-08-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='target',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
