# Generated by Django 5.1 on 2025-08-16 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_alter_fundraiser_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraiser',
            old_name='goal',
            new_name='destination_year',
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('anonymous', models.BooleanField()),
                ('fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pledges', to='fundraisers.fundraiser')),
            ],
        ),
    ]
