# Generated by Django 5.1 on 2025-08-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_alter_fundraiser_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='destination_year',
            field=models.IntegerField(),
        ),
    ]
