# Generated by Django 5.1 on 2025-08-16 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_rename_goal_fundraiser_destination_year_pledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='fundraiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='fundraisers.fundraiser'),
        ),
    ]
